type ChartItem = {
  name: string;
  children?: ChartItem[];
};

export const InterventionData: ChartItem = {
  name: 'ID Interventions',
  children: [
    {
      name: 'Vetted',
      children: [
        {
          name: 'Sleep',
          children: [{ name: 'Eight Sleep' }, { name: 'Red Lighting (Evening)' }, { name: 'Blue Light Filter f.lux' }],
        },
        { name: 'Longevity-focused exercise' },
        {
          name: 'Skincare',
          children: [
            { name: 'Retinol' },
            { name: 'Tretinoin' },
            { name: ' Accutane 40mg per week' },
            { name: 'Red Light Therapy 12-min 3 sessions / week' },
            { name: 'Tixel' },
            { name: 'Sofwave' },
            { name: 'Sculptra' },
            { name: 'Under Eye PRF (Platelet-Rich Fibrin)' },
          ],
        },
        {
          name: 'Haircare',
          children: [
            { name: 'Red light cap 6 min (Kerafactor) 1x/day' },
            { name: 'Customized Hair Growth Topical and Genetic Test, Roots by Genetic Arts' },
            { name: 'Minoxidil 3.5mg' },
            { name: ' Scalp massage' },
          ],
        },
        { name: 'Physio devices' },
      ],
    },
    {
      name: 'Novel',
      children: [
        {
          name: 'Gene Threrapy',
          children: [{ name: 'Plasmid' }, { name: 'Follistatin' }, { name: 'Klotho' }, { name: 'Testosterone' }],
        },
        {
          name: 'Oxygen',
          children: [{ name: 'Hyperbaric Oxygen' }, { name: 'Interval Hypoxia-Hyperoxia Therapy IHHT' }],
        },
        {
          name: 'Anti-aging',
          children: [{ name: 'Exosome' }, { name: 'Rapamycin' }, { name: '17α-Estradiol (17aE2) transdermally 2mg' }],
        },
        { name: 'ZField electromagnetic pulses' },
        { name: 'Whole-Body Cryotherapy' },
        { name: 'Cryolipolysis & ZWave' },
        {
          name: 'Stem Cell',
          children: [{ name: 'iPSC HebeCell' }, { name: 'MSC' }, { name: 'NK' }, { name: 'StemFit' }, { name: 'IV / Joint' }],
        },
        { name: 'Infusion IV' },
        { name: 'Augmentation', children: [{ name: 'Exoskeleton' }] },
      ],
    },
  ],
};

export const SupplementData: ChartItem = {
  name: 'ID Supplement',
  children: [
    { name: 'Glucosamine Sulfate Potassium 1.5g' },
    { name: 'Creatine Monohydrate (CreaPure) 5g' },
    { name: 'Sodium Hyaluronate (Hyaluronic acid) 120mg' },
    { name: 'Taurine 1.5g' },
    { name: 'L-Lysine HCL 1g' },
    { name: 'Glycine 1.2g' },
    { name: 'L-Theanine 200mg' },
    { name: 'Vitamin C (Ascorbic Acid) 250mg' },
    { name: 'Magnesium Citrate Anhydrous 150mg' },
    { name: 'Ashwagandha KSM66 Root Extract 600mg' },
    { name: 'CaAKG 2g  Calcium 350mg' },
    { name: 'Calcium Carbonate Dicalcium Phosphate 250mg' },
    { name: 'L-Glutathione Reduced 250mg' },
    { name: 'Allulose 4g' },
    { name: 'Collagen protein 22 g' },
    { name: 'Prebiotic Galactooligosaccharides GOS 2.5g' },
    { name: 'Inulin 5g' },
    {
      name: 'Cocoa Powder (Non-Alkalised) 6g',
      children: [
        { name: 'Cocoa flavanols 300mg' },
        { name: ' Copper 0.4mg' },
        { name: 'Omega 3, ALA 3g' },
        { name: 'Allulose 11g' },
        { name: 'Fibre 4g' },
      ],
    },
    { name: 'Grape seed extract (GSE) Polyphenols 300mg' },
    { name: 'Pomegranate Juice Extract 300mg' },
    { name: 'Cinnamon (Ceylon) Organic 1.2g' },
    { name: 'Sunflower Lecithin non-GMO 5g' },
    { name: 'Choline (vitamin B4) 150mg' },
    { name: 'Milled Golden Flaxseed 5g' },
    { name: 'Secoisolariciresinol diglucoside (SGD) lignan 50mg' },
    { name: 'Pea Protein Isolate, Bakers Yeast Protein Isolate, Hemp Protein blend 26g' },
    { name: 'Acarbose 200 mg (Rx)' },
    { name: 'Omega‑3, EPA/DHA/DPA 1600mg' },
    { name: 'Kyolic 2.4 g' },
    { name: 'Metformin 1000 mg (Rx)' },
    { name: 'Nicotinamide Ribose Chloride Niagen NR 750mg' },
    { name: 'NMN 500mg' },
    {
      name: 'Plasmalogens',
      children: [{ name: 'Glia 1ml' }, { name: 'Neuro 1ml' }],
    },
    { name: 'ProButyrate 600mg' },
    {
      name: 'EVOO',
      children: [{ name: 'Polyphenols HPLC (NOT NMR)' }, { name: 'Oleic Acid' }],
    },
    { name: 'Proferrin 21mg' },
    { name: 'N-Acetyl-L-Cysteine NAC 3000mg' },
    { name: 'Vitamin B1, Thiamine HCL 1.1mg' },
    { name: 'Vitamin B2, Riboflavin 1.4mg' },
    { name: 'Vitamin B3, Niacinamide 15mg' },
    { name: 'Vitamin B5, D-Calcium Pantothenate 6mg' },
    { name: 'Vitamin B6, Pyridoxine HCL 1.4mg' },
    { name: 'Vitamin B7, Biotin 50mcg' },
    { name: 'Vitamin B9, Calcium L-5-Methyltetrahydrofolate 200mcg' },
    { name: 'Vitamin B12, Methylcobalamin 125mcg' },
    { name: 'Vitamin D3, VegD3 2700IU' },
    { name: 'Vitamin E, d-alpha tocopherol, natural 67mg' },
    { name: 'Boron, as Boron Glycinate 3mg' },
    { name: 'Manganese, as Manganese Citrate 1mg' },
    { name: 'Zinc, as Zinc Bisglycinate 15mg' },
    { name: 'Iodide, as Potassium Iodide 200mcg' },
    { name: 'Lithium, as Lithium Orotate 1mg' },
    { name: 'Selenium, as L-selenomethionine 30mcg' },
    { name: 'Ubiquinol (CoQ10 Reduced) 50mg' },
    { name: 'Glucoraphanin, from broccoli 20mg' },
    { name: 'Rhodiola rosea extract, 3% Rosavins/1% Salidroside 300mg' },
    { name: 'Fisetin, from Smoketree 100mg' },
    { name: 'Spermidine, as Spermidine trihydrochloride 10mg' },
    { name: 'Genistein, from Japonica 300mg' },
    { name: 'Luteolin 100mg' },
    { name: 'Lactobacillus acidophilus probiotic 4 billion CFU' },
    { name: 'Lutein 15mg' },
    { name: 'Zeaxanthin 3mg' },
    { name: 'Lycopene 15mg' },
    { name: 'Vit K1 1.5mg' },
    { name: 'VIT K2 - MK4 5mg' },
    { name: 'VIT K2 - MK7 0.6mg' },
    { name: 'Astaxanthin, from algae 12mg' },
    { name: 'Ginger extract, high gingerol content equivalent to 1-2g ginger powder 400mg' },
    { name: 'Curcuminoids (75% curcumin, 20% demethoxycurcumin, 5% bisdemethoxycurcumin) 220mg' },
    { name: 'Red Yeast Rice (2% Monacolin K) 500mg' },
    { name: 'Monacolin K 10mg' },
    { name: 'Odorless Garlic Powdered Extract, 12:1 100mg' },
  ],
};

export const BiomarkerData: ChartItem = {
  name: 'ID Biomarker Tracking',
  children: [
    {
      name: 'Hormone Panel',
      children: [
        { name: 'Testosterone ' },
        { name: 'E2 Estradiol ' },
        { name: 'SHBG Sex Hormone-Binding Globulin' },
        { name: 'FSH Follicle-Stimulating Hormone' },
        { name: 'LH Luteinizing Hormone' },
        { name: 'Cortisol' },
        { name: 'DHEA-S Dehydroepiandrosterone Sulfate' },
        { name: 'IGF-1 Insulin-like Growth Factor 1' },
        { name: 'hGH Human Growth Hormone' },
      ],
    },
    {
      name: 'Metabolic',
      children: [
        { name: 'Resting Metabolic Rate (RMR)' },
        { name: 'VO2Max (COSMED)' },
        { name: 'Gut Microbiome' },
        { name: 'Fasting Insulin' },
        { name: 'Homeostatic Model Assessment for Insulin Resistance HOMA-IR' },
      ],
    },
    {
      name: 'Aging',
      children: [{ name: 'Epigenetic clock (DNA methylation)' }, { name: 'Telomere length' }],
    },
    {
      name: 'Allergy Panel',
      children: [
        { name: 'Immunoglobulin E (IgE) antibodies' },
        { name: 'dust mites, pollen, animals, gluten, milk, eggs, nuts, buckwheat, etc.' },
      ],
    },
    {
      name: 'Cancer Markers',
      children: [
        { name: 'LucenceINSIGHT™ PLUS (circulating tumor DNA) for 50 cancers' },
        { name: 'Alpha Fetoprotein (AFP, liver or testicular)' },
        { name: 'Carcinoembryonic Antigen (CEA, Colon colorectal)' },
        { name: 'CA 19-9 (Pancreas and others)' },
        { name: 'CA125 (Ovary, for Female only)' },
        { name: 'PSA (Prostate, for Male only)' },
        { name: 'EBV EA IgA (Nose nasopharyngeal)' },
        { name: 'B-HCG (testicular)' },
      ],
    },
    {
      name: 'Diabetes Panel',
      children: [
        { name: 'Fasting Blood Glucose' },
        { name: 'HBA1C' },
        { name: 'Oral Glucose Tolerance Test (OGTT) 3 additional blood draws over 1.5h' },
      ],
    },
    {
      name: 'Blood Test',
      children: [
        { name: 'Calcium Magnesium Phosphate' },
        {
          name: 'Hematology',
          children: [{ name: 'Full Blood Count' }, { name: 'ESR (Erythrocyte Sedimentation Rate)' }],
        },
        {
          name: 'Iron Panel',
          children: [{ name: 'Vitamin B12' }, { name: 'Folic Acid' }, { name: 'TIBC' }, { name: 'Ferritin' }],
        },
        {
          name: 'Renal Function',
          children: [{ name: 'Urea' }, { name: 'Creatinine' }, { name: 'Potassium' }, { name: 'Chloride' }, { name: 'Sodium' }],
        },
        {
          name: 'Toxicology',
          children: [{ name: 'Serum Copper' }, { name: 'Serum Zinc' }],
        },
        {
          name: 'Lipid Profile',
          children: [
            { name: 'Fasting Blood Cholesterol' },
            { name: 'Triglycerides' },
            { name: 'HDL & LDL Cholesterol' },
            { name: 'Cholesterol / HDL Ratio' },
            { name: 'Omega-3 fatty acids (EPA and DHA)' },
          ],
        },
        {
          name: 'Cardiac Profile',
          children: [
            { name: 'High Sensitive CRP (hs-CRP)' },
            { name: 'Homocysteine' },
            { name: 'Apolipoprotein A1' },
            { name: 'Apolipoprotein B' },
            { name: 'Lipoprotein (a)' },
            { name: 'Apolipoprotein B/A1 Ratio' },
          ],
        },
        {
          name: 'Liver Profile',
          children: [
            { name: 'Total Protein' },
            { name: 'Albumin' },
            { name: 'Globulin' },
            { name: 'A/G Ratio' },
            { name: 'Total Bilirubin' },
            { name: 'Alkaline Phosphatase' },
            { name: 'Aspartate Aminotransferase (AST) / SGOT' },
            { name: 'Alanine Aminotransferase (ALT) / SGPT' },
            { name: 'Gamma-Glutamyl Transferase GGT' },
          ],
        },
        {
          name: 'Thyroid Profile',
          children: [{ name: 'Free T3' }, { name: 'Free T4' }, { name: 'Thyroid Stimulating Hormone (TSH)' }],
        },
        {
          name: 'Hepatitis Profile',
          children: [{ name: 'Hepatitis A IgG Antibody' }, { name: 'Hepatitis Bs Antigen' }, { name: 'Hepatitis Bs Antibody' }],
        },
      ],
    },
    {
      name: 'Urine Analysis',
      children: [
        { name: 'Urine FEME' },
        { name: 'Albumin - Urine (Microalbumin)' },
        { name: 'Creatinine - Urine' },
        { name: 'Urine Microalbumin / Urine Creatinine' },
        { name: 'Urine Microalbumin / Creatinine Ratio' },
        { name: 'Estimated Glomerular Filtration Rate (eGFR)' },
        { name: 'Ketones' },
        { name: 'Nitrite' },
        { name: 'Leukocytes' },
        { name: 'Hyaline Casts' },
        { name: 'Epithelial Cells' },
      ],
    },
    {
      name: 'Stool Analysis',
      children: [{ name: 'Stool FEME and Occult Blood' }],
    },
    {
      name: 'X-Ray',
      children: [{ name: 'X-Ray Chest' }, { name: 'Mammogram (Female)' }],
    },
    {
      name: 'Ultrasound',
      children: [
        { name: 'Ultrasound Abdomen' },
        { name: 'Ultrasound Thyroid' },
        { name: 'Liver elastography with attenuation' },
        { name: 'Ultrasound Prostate (Male)' },
        { name: 'Ultrasound Scrotum (Male)' },
        { name: 'Ultrasound Breast (Female)' },
        { name: 'Ultrasound Pelvis (Female)' },
      ],
    },
    {
      name: 'Cardiology',
      children: [
        { name: 'Coronary Artery Calcium Score' },
        { name: 'Echocardiogram' },
        { name: 'Coronary CT Angiograms' },
        { name: 'Treadmill Stress Test' },
        { name: 'Holter Monitor Test' },
        { name: 'ECG 12-Lead' },
        { name: 'Haemodynamics' },
      ],
    },
    {
      name: 'Lung Function',
      children: [{ name: 'Spirometry' }, { name: 'Exhaled Nitric Oxide' }],
    },
    { name: 'Nighttime Erections' },
    { name: 'Sleep Study' },
    {
      name: 'Audiology',
      children: [{ name: 'Audiometry' }],
    },
    {
      name: 'Ophthalmology',
      children: [
        { name: 'Visual acuity' },
        { name: 'Auto-refraction' },
        { name: 'Subjective refraction' },
        { name: 'Slit-lamp examination' },
        { name: 'Refraction with cycloplegia' },
        { name: 'Ocular motility evaluation' },
        { name: 'Tonometry' },
      ],
    },
    {
      name: 'Dermatology',
      children: [{ name: 'Mole check' }],
    },
  ],
};
