export enum MessageType {
  SWITCH_MODEL = 'SWITCH_MODEL', // 切换模型
  SYNC_CAMERA = 'SYNC_CAMERA', // 同步摄像机
  ALLOW_OPERATION = 'ALLOW_OPERATION', // 允许操作
  SWITCH_ANATOMY_MODULE = 'SWITCH_ANATOMY_MODULE', // 切换解刨模块
  SWITCH_CAMERA = 'SWITCH_CAMERA', // 切换相机视角
  RESET_ANIMATION = 'RESET_ANIMATION', // 重置动画
  SIRI_WAVE_CONFIG = 'SIRI_WAVE_CONFIG', // siri wave 设置
  PODCAST_DURATION = 'PODCAST_DURATION', // 播放时间
  CLOSE_SUBSCRIBE = 'CLOSE_SUBSCRIBE', // 关闭订阅弹窗
  CHANGE_PLAY_STATUS = 'CHANGE_PLAY_STATUS', // 修改播放状态
}
