export const VISION_GL_CONFIG = {
  mobileLoopAnim: {
    camera: {
      position: [
        { x: -1, y: 2, z: 10 },
        { x: 1, y: 2, z: 10 },
        { x: 2, y: -2, z: 10 },
        { x: -1, y: -2, z: 10 },
      ],
    },
  },
} as const;

const TRANSMISSION_KEYFRAMES = [
  {
    transmission: 1,
    roughness: 0.1,
    thickness: 10,
    ior: 1.5,
    chromaticAberration: 1,
    anisotropy: 0,
    distortion: 1,
    distortionScale: 0.15,
    temporalDistortion: 0.1,
    clearcoat: 1,
    metalness: 0.1,
  },
  {
    transmission: 1,
    roughness: 0.0,
    thickness: 10,
    ior: 1,
    chromaticAberration: 1,
    anisotropy: 1,
    distortion: 1,
    distortionScale: 1,
    temporalDistortion: 0.1,
    clearcoat: 1,
    metalness: 0,
  },
  {
    transmission: 1,
    roughness: 0.0,
    thickness: 10,
    ior: 3.16,
    chromaticAberration: 1,
    anisotropy: 1,
    distortion: 1,
    distortionScale: 0.1,
    temporalDistortion: 0.1,
    clearcoat: 1,
    metalness: 0,
  },
  {
    transmission: 1,
    roughness: 0.0,
    thickness: 10,
    ior: 2.28,
    chromaticAberration: 1,
    anisotropy: 0,
    distortion: 1,
    distortionScale: 0.3,
    temporalDistortion: 0.1,
    clearcoat: 1,
    metalness: 0,
  },
  {
    transmission: 1,
    roughness: 0.0,
    thickness: 10,
    ior: 1,
    chromaticAberration: 1,
    anisotropy: 1,
    distortion: 1,
    distortionScale: 0.5,
    temporalDistortion: 0.1,
    clearcoat: 1,
    metalness: 0,
  },
  {
    transmission: 1,
    roughness: 0,
    thickness: 10,
    ior: 1.5,
    chromaticAberration: 0.5,
    anisotropy: 0.1,
    distortion: 0,
    distortionScale: 0.5,
    temporalDistortion: 0.1,
    clearcoat: 0,
    metalness: 0.1,
  },
] as const;
const CONFIG_INDEX = Math.floor(Math.random() * TRANSMISSION_KEYFRAMES.length);
export const RANDOM_CONFIG = TRANSMISSION_KEYFRAMES[CONFIG_INDEX];
